### ISSUE TITLE
Ubuntu等のLinux系の構築・運用・保守について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS-3#1]

**Comment by yamamoto-ryuzo** [comment]
Ubuntu等のLinux系の構築・運用・保守は可能でしょうか。
可能な場合は，ディストリビューションを教えてください。
DockerでもOKです。

**Comment by MasanobuGai** [comment]
Linux系は以下の構築運用保守経験があります。

RedHat (CentOS) 5、6、7
　※RedHat 8 系は同系列の無償版CentOS 8がなくなったため扱っていません。
Ubuntu 20.04 LTS


当社は業務系としての構築が多いため、概ね構築経験としては以下の内容です。

・ウェブサーバー (Apache2.4系)
・メールサーバー (Postfix)
・データベースサーバー (PostgreSQL、MySQL、MariaDB、Oracle)
・ファイルサーバー (SAMBA)
　　※SAMBA はここ数年取り扱いはありません。

**Comment by yamamoto-ryuzo** [comment]
了解いたしました。
確定内容
・Ubuntu 20.04 LTS
・ウェブサーバー (Apache2.4系)
・データベースサーバー (PostgreSQL、MySQL、MariaDB、Oracle)

検討中の内容
・メールサーバー (Postfix)
