### ISSUE TITLE
LizmapServerの管理について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS-3#2]
先ほど教えていただいた実績によりますと。
おそらく，下記内容は十分理解できるものと思われます。
このサーバーの管理はどのような感じでしょうか。
ご検討ください。
https://github.com/yamamoto-ryuzo/Lizmap-installation-Japanese-memo

**Comment by MasanobuGai** [comment]
LIZMAP Web Client のカスタマイズ以外は問題なさそうです。
PHP、Python環境の構築も要件が資料化されているようですので問題ありません。

1点確認です。
本資料ではWebArenaでVPSによる構築となっておりましたが
実構築環境もVPSでしょうか？
それともオンプレミスのサーバーとなりますか？

**Comment by yamamoto-ryuzo** [comment]
基本カスタマイズは3LIZにお願いするようになります。
https://www.lizmap.com/en/

サーバーは，VPSもしくは庁内のオンプレミスを検討しています。
遠隔保守を考えるとVPSが安くなりそうです。

WebArenaはたまたま，私の趣味でそちらを使っているだけです。
こだわりはありません。
https://www.facebook.com/groups/lizmapusergroupjapan/
http://lizmap.yamakun.net/

**Comment by yamamoto-ryuzo** [comment]
御社としては
VPSもしくは庁内のオンプレミス（遠隔は困難だと思います）
どちらがよいでしょうか？

**Comment by MasanobuGai** [comment]
VPSが可能であればこちらの方がリモートメンテナンスに対応しやすいと思いますので
VPSがいいと思います。

**Comment by yamamoto-ryuzo** [comment]
下記VPSを予定しております。
https://github.com/city-soja-chiiki/QGIS-3/issues/3
