### ISSUE TITLE
VPS等のインターネット環境の構築について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS-3#3]
現在，LIZMAPは　https://www.acugis.com/
　のクラウドを利用しておりますが，今後機能拡充を検討しております。
そこで，VPS　もしくは　庁内サーバー　を検討しておりますが，
WillWaveでVPS実績のあるところを教えて下さい。

参考までに，動作しているLIZMAPは下記です。
https://soja.gis-cdn.net/

**Comment by MasanobuGai** [comment]
当社では AWS のパートナーとして構築運用保守をさせていただいております。
他ではニフティクラウドも運用実績がございます。

**Comment by yamamoto-ryuzo** [comment]
ニフティクラウド
https://pfs.nifcloud.com/price/
だと思うのですが，これって何がいいのかちょっと見ただけでは判別つかなかったのですが，よい特徴は何でしょうか？
たまたま，どこかの会社に頼まれた程度でしょうか？

**Comment by MasanobuGai** [comment]
ニフティはおっしゃる通り、クライアントに依頼されての案件で対応しました。
あまり細かい融通が効かないという点ではおすすめしかねます。。。
通信量による従量課金がない点が唯一？いいところでしょうか。

AWSは円安の影響が大きいのでなかなか薦めにくいというのはあります。。。

**Comment by yamamoto-ryuzo** [comment]
VPSの場合，御社に特に実績に多いものがないのであれば，インターネットの評価から単純に
https://web.arena.ne.jp/indigopro/
![image](https://user-images.githubusercontent.com/86514652/197709100-49b1e8a8-8a8b-4b53-983a-7e864b53a980.png)
https://vps.sakura.ad.jp/specification/
![image](https://user-images.githubusercontent.com/86514652/197709384-f2377bba-149d-439c-a841-d09d8fffd666.png)
見た目だけのスペックではさくらの方が安いですが・・・使わないとわからないところが大きいのでどっちでもOKです。

候補としてはどうでしょうか？

**Comment by MasanobuGai** [comment]
WebArenaはNTT系列だったんですね。。。

これまでNTT系列のVPSサービスで2サービスほど運用で利用しましたが、そのどちらもサービス終了で移行を余儀なくされた経緯があります。

個人的な感想ですが、NTTはこういったサービスに企業として責任感がないように思われますので、国内では相当古くからサービス提供を継続されているさくらがよろしいかと思います。

**Comment by yamamoto-ryuzo** [comment]
雰囲気からするとLGWAN等への積極的な関わり合い等を考えると「さくら」が安心かもしれません。
まったく、懲りないので「さくら」でよいでしょうか？
https://cloud.sakura.ad.jp/specification/detail/
たぶん、「さくら」なら回線の太い「クラウド」になります。
とりあえずトライアルの委託を出してもいいです。
![image](https://user-images.githubusercontent.com/86514652/197905371-574d49ab-6e00-4b38-806e-07cf6064d72a.png)
まずは、この環境でのLIZMAP初期導入及び月額保守とうの見積もりをお願いします。
今後は、
https://github.com/city-soja-chiiki/QGIS-3/issues/2
に移行します。

**Comment by MasanobuGai** [comment]
すみません、現在算定していますので少々お待ちください。
さくらの契約管理等も当社の方で行うという認識でお見積りさせていただきます。
齟齬あればご指摘ください。

**Comment by yamamoto-ryuzo** [comment]
さくらも御社でお願いいたします。

**Comment by MasanobuGai** [comment]
大変遅くなりました。

LIZMAP環境の初期導入及び月額のお見積りです。
QGIS本体の運用・保守につきましては、Python経験がないこと、現時点で全体が見通せていないことを含め概算です。
Pythonについては複雑なものでなければそれほど難しくはないと思っています。

[LIZMAP環境運用御見積書.pdf](https://github.com/city-soja-chiiki/QGIS-3/files/9916507/LIZMAP.pdf)
[LIZMAP環境初期導入御見積書.pdf](https://github.com/city-soja-chiiki/QGIS-3/files/9916508/LIZMAP.pdf)

**Comment by yamamoto-ryuzo** [comment]
こういうことでよろしかったでしょうか。
また，こちらはいいのですが，見ようと思えば丸見えなので，見積りはメールでもokです。
　メールの場合は
　soja.road@gmail.com
　chiiki@city.soja.okayama.jp
両方へお願いします。

[道路・水路台帳サーバー見積.xlsx](https://github.com/city-soja-chiiki/QGIS-3/files/9920596/default.xlsx)

**Comment by yamamoto-ryuzo** [comment]
ところで，一応さくらの費用も入れておいてください。

**Comment by MasanobuGai** [comment]
SSDミラー化の方にて確認させていただいたお見積もりを含め訂正させていただいております。
https://github.com/city-soja-chiiki/QGIS-3/issues/7
