### ISSUE TITLE
対応可能言語について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS-3#4]
QGIS起動管理
　DOSコマンド
　powershellコマンド（JAVA）　簡易なもの

QGISプラグイン開発
　python

ですが，対応可能な言語はありますか。

**Comment by MasanobuGai** [comment]
当社での対応可能言語は以下となります。
※Python、Rubyは実績がありません。

・Java
・PHP
・C#
・JavaScript


Shellコマンドとしては以下は可能です。

・Linux Shell コマンド
・Windows DOS コマンド
・Windows Power Shell コマンド

**Comment by yamamoto-ryuzo** [comment]
> Shellコマンドとしては以下は可能です。
> 
> ・Linux Shell コマンド ・Windows DOS コマンド ・Windows Power Shell コマンド

https://github.com/city-soja-chiiki/QGIS-3/issues/5
に移行します。
