### ISSUE TITLE
QGIS起動管理について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS-3#5]
QGISのLGWANの保守になります。
https://github.com/yamamoto-ryuzo/yr-qgis-portable-launcher
です。
が，初歩的なQGIS知識は必要となります。
そういう意味ではアイ・サポートさんの方が適しているようでもある案件です。

とりあえず，この程度のBATの管理及びQGISのバージョンアップについてご検討ください。

**Comment by yamamoto-ryuzo** [comment]
https://github.com/city-soja-chiiki/QGIS/tree/main/2.QGIS%E6%9C%AC%E4%BD%93%E3%81%AE%E4%BF%9D%E5%AE%88
も一読ください。

**Comment by MasanobuGai** [comment]
確認させていただきました。

経験のある業者さんよりは理解するまでに当初時間を要する所もあるかもしれませんが、対応可能かと思います。

**Comment by yamamoto-ryuzo** [comment]
私のお手製なので、経験ある業者いません・・・
実際の作業は、定期的にQGIS及びプラグインの最新版をダウンロードして環境設定部分を更新の上、LGWANに配信していただく、ことになります。
最低限、年4回程度の更新を考えております。
今後は、仕様書の作成に入ります。
よろしくお願いいたします。
昨日、QGIS本体がバージョンアップされたので、早速、このバージョンアップから委託に出すかもしれません。
その際は、よろしくお願いいたします。

**Comment by MasanobuGai** [comment]
承知いたしました。
