### ISSUE TITLE
Python開発について

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS-3#6]
直近では，保守1件，開発１件あります。
が，オープンソースが基本ですがOKでしょうか。
基本，ＱＧＩＳの
https://github.com/yamamoto-ryuzo/yr-qgis-portable-launcher
の標準システム構築です。
オープンソースでないプラグインも保有しているのですが，結局，データの受け渡し等でNGなため，不便なため，事実上使えないです。（残念）

・保守
　https://github.com/yamamoto-ryuzo/GEO-search-plugin
　の3.22対応やそのたもろもろ。
・開発
　QGIS起動時のマクロ作成です。
　オープン時：現在の表示範囲をQGIＳグローバル変数から読込，その範囲で表示
　クローズ時：現在の表示範囲をQGIＳグローバル変数に保存
　目的：プロジェクトを変更しても，同じ位置を表示されせる。　
![image](https://user-images.githubusercontent.com/86514652/199500526-ec129d3e-d738-4d43-8861-3bdf440e903e.png)

**Comment by MasanobuGai** [comment]
オープンソース利用でも開発可能です。

当社で現在請け負っている案件が飽和しておりますので年始あたりまでお時間をいただけると幸いです。

**Comment by yamamoto-ryuzo** [comment]
年始によろしくお願いいたします。
