### ISSUE TITLE
このサイトの利用方法の確認

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS-3#8]
現在，このリポジトリ
https://github.com/city-soja-chiiki/QGIS-3
は，WillWave専用のリポジトリとして考えております。
ついでに　タイトルも　「3.サーバー WillWave打合用専用　掲示板」　に変更しておきました。
未回答のISSUESについても，宛先はWillWave宛です。
よろしくお願いいたします。
念のため，WATCHEは「ALL　ACTIVITY」に設定お願いいたします。

![image](https://user-images.githubusercontent.com/86514652/201338893-bee11982-c013-4a12-a9c5-be3d6efb4a9c.png)

**Comment by MasanobuGai** [comment]
All Activityに設定を変更しておきました。

また確認、解答が遅くて申し訳ございません。。。
この時期。。。例年10月から12月頭頃まで出張で殆ど岡山に居ないもので。

**Comment by yamamoto-ryuzo** [comment]
繋がっていればOKです！
体調にはお気を付けください。
